## Custom features from Pandas
See Pandas help here :https://pandas.pydata.org/pandas-docs/stable/getting_started/tutorials.html

In [1]:
import pandas



Load databases .cvs

In [2]:
from pandas import read_csv
df = read_csv('https://oml-data.s3.amazonaws.com/kaggle-give-me-credit-train.csv')

Checking columns of tables

In [3]:
df.head(5)

,Unnamed: 0,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents,SeriousDlqin2yrs
0,1,0.766127,45,2,0.802982,9120.0,13,0,6,0,2.0,1
1,2,0.957151,40,0,0.121876,2600.0,4,0,0,0,1.0,0
2,3,0.658180,38,1,0.085113,3042.0,2,1,0,0,0.0,0
3,4,0.233810,30,0,0.036050,3300.0,5,0,0,0,0.0,0
4,5,0.907239,49,1,0.024926,63588.0,7,0,1,0,0.0,0

Checking statistics of column

In [4]:
df.describe()

,Unnamed: 0,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents,SeriousDlqin2yrs
count,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,1.202690e+05,150000.000000,150000.000000,150000.000000,150000.000000,146076.000000,150000.000000
mean,75000.500000,6.048438,52.295207,0.421033,353.005076,6.670221e+03,8.452760,0.265973,1.018240,0.240387,0.757222,0.066840
std,43301.414527,249.755371,14.771866,4.192781,2037.818523,1.438467e+04,5.145951,4.169304,1.129771,4.155179,1.115086,0.249746
min,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,37500.750000,0.029867,41.000000,0.000000,0.175074,3.400000e+03,5.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,75000.500000,0.154181,52.000000,0.000000,0.366508,5.400000e+03,8.000000,0.000000,1.000000,0.000000,0.000000,0.000000
75%,112500.250000,0.559046,63.000000,0.000000,0.868254,8.249000e+03,11.000000,0.000000,2.000000,0.000000,1.000000,0.000000
max,150000.000000,50708.000000,109.000000,98.000000,329664.000000,3.008750e+06,58.000000,98.000000,54.000000,98.000000,20.000000,1.000000

Checking types of columns

In [5]:
df.dtypes

Unnamed: 0                                int64
RevolvingUtilizationOfUnsecuredLines    float64
age                                       int64
NumberOfTime30-59DaysPastDueNotWorse      int64
DebtRatio                               float64
MonthlyIncome                           float64
NumberOfOpenCreditLinesAndLoans           int64
NumberOfTimes90DaysLate                   int64
NumberRealEstateLoansOrLines              int64
NumberOfTime60-89DaysPastDueNotWorse      int64
NumberOfDependents                      float64
SeriousDlqin2yrs                          int64
dtype: object

Insert new features (new columns)

In [6]:
df['NumberOfTimes90DaysLate_TOTAL'] = df['NumberOfTime30-59DaysPastDueNotWorse'] + df['NumberOfTime60-89DaysPastDueNotWorse']+df['NumberOfTimes90DaysLate']
df['IsOld']=df['age']>70

Checking new table and its new features

In [7]:
df.head(5)

,Unnamed: 0,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents,SeriousDlqin2yrs,NumberOfTimes90DaysLate_TOTAL,IsOld
0,1,0.766127,45,2,0.802982,9120.0,13,0,6,0,2.0,1,2,False
1,2,0.957151,40,0,0.121876,2600.0,4,0,0,0,1.0,0,0,False
2,3,0.658180,38,1,0.085113,3042.0,2,1,0,0,0.0,0,2,False
3,4,0.233810,30,0,0.036050,3300.0,5,0,0,0,0.0,0,0,False
4,5,0.907239,49,1,0.024926,63588.0,7,0,1,0,0.0,0,1,False

In [8]:
df.describe()

,Unnamed: 0,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents,SeriousDlqin2yrs,NumberOfTimes90DaysLate_TOTAL
count,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,1.202690e+05,150000.000000,150000.000000,150000.000000,150000.000000,146076.000000,150000.000000,150000.000000
mean,75000.500000,6.048438,52.295207,0.421033,353.005076,6.670221e+03,8.452760,0.265973,1.018240,0.240387,0.757222,0.066840,0.927393
std,43301.414527,249.755371,14.771866,4.192781,2037.818523,1.438467e+04,5.145951,4.169304,1.129771,4.155179,1.115086,0.249746,12.466204
min,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,37500.750000,0.029867,41.000000,0.000000,0.175074,3.400000e+03,5.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,75000.500000,0.154181,52.000000,0.000000,0.366508,5.400000e+03,8.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
75%,112500.250000,0.559046,63.000000,0.000000,0.868254,8.249000e+03,11.000000,0.000000,2.000000,0.000000,1.000000,0.000000,0.000000
max,150000.000000,50708.000000,109.000000,98.000000,329664.000000,3.008750e+06,58.000000,98.000000,54.000000,98.000000,20.000000,1.000000,294.000000

In [9]:
df.dtypes

Unnamed: 0                                int64
RevolvingUtilizationOfUnsecuredLines    float64
age                                       int64
NumberOfTime30-59DaysPastDueNotWorse      int64
DebtRatio                               float64
MonthlyIncome                           float64
NumberOfOpenCreditLinesAndLoans           int64
NumberOfTimes90DaysLate                   int64
NumberRealEstateLoansOrLines              int64
NumberOfTime60-89DaysPastDueNotWorse      int64
NumberOfDependents                      float64
SeriousDlqin2yrs                          int64
NumberOfTimes90DaysLate_TOTAL             int64
IsOld                                      bool
dtype: object

Put the "output" at the end of the table

In [10]:
new_order = [0,1,2,3,4,5,6,7,8,9,10,12,13,11]
df1= df[df.columns[new_order]]  
df1.dtypes

Unnamed: 0                                int64
RevolvingUtilizationOfUnsecuredLines    float64
age                                       int64
NumberOfTime30-59DaysPastDueNotWorse      int64
DebtRatio                               float64
MonthlyIncome                           float64
NumberOfOpenCreditLinesAndLoans           int64
NumberOfTimes90DaysLate                   int64
NumberRealEstateLoansOrLines              int64
NumberOfTime60-89DaysPastDueNotWorse      int64
NumberOfDependents                      float64
NumberOfTimes90DaysLate_TOTAL             int64
IsOld                                      bool
SeriousDlqin2yrs                          int64
dtype: object

In [11]:
df1.head(5)

,Unnamed: 0,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents,NumberOfTimes90DaysLate_TOTAL,IsOld,SeriousDlqin2yrs
0,1,0.766127,45,2,0.802982,9120.0,13,0,6,0,2.0,2,False,1
1,2,0.957151,40,0,0.121876,2600.0,4,0,0,0,1.0,0,False,0
2,3,0.658180,38,1,0.085113,3042.0,2,1,0,0,0.0,2,False,0
3,4,0.233810,30,0,0.036050,3300.0,5,0,0,0,0.0,0,False,0
4,5,0.907239,49,1,0.024926,63588.0,7,0,1,0,0.0,1,False,0

In [12]:
df1.describe()

,Unnamed: 0,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents,NumberOfTimes90DaysLate_TOTAL,SeriousDlqin2yrs
count,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,1.202690e+05,150000.000000,150000.000000,150000.000000,150000.000000,146076.000000,150000.000000,150000.000000
mean,75000.500000,6.048438,52.295207,0.421033,353.005076,6.670221e+03,8.452760,0.265973,1.018240,0.240387,0.757222,0.927393,0.066840
std,43301.414527,249.755371,14.771866,4.192781,2037.818523,1.438467e+04,5.145951,4.169304,1.129771,4.155179,1.115086,12.466204,0.249746
min,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,37500.750000,0.029867,41.000000,0.000000,0.175074,3.400000e+03,5.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,75000.500000,0.154181,52.000000,0.000000,0.366508,5.400000e+03,8.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
75%,112500.250000,0.559046,63.000000,0.000000,0.868254,8.249000e+03,11.000000,0.000000,2.000000,0.000000,1.000000,0.000000,0.000000
max,150000.000000,50708.000000,109.000000,98.000000,329664.000000,3.008750e+06,58.000000,98.000000,54.000000,98.000000,20.000000,294.000000,1.000000

Save new file

In [13]:
df1.to_csv('Train_Full_New1.csv')